### ISSUE TITLE
Error: EISDIR illegal operation on a directory, open '{path}/{to}/{extension-dir}' 

### ISSUE THREAD

**Issue by ExpressDead** [microsoft/azure-devops-extension-sample#37]
I'm running into an issue trying to use the recommended path to initialize an extension. 

Each attempt at running `tfx extension init` results in error:

`error: Error: Error unzipping /{path/azure-devops-extension-sample.zip: Error: EISDIR: illegal operation on a directory, open '/{path}/`

While troubleshooting with the `--trace-level=debug` I noticed what appears to be a delete operation after the zipped source is downloaded, but before the unzip operation. 

`Downloading sample package from https://codeload.github.com/Microsoft/azure-devops-extension-sample/zip/master
Package downloaded to {path}/azure-devops-extension-sample.zip (120 kB)
2019-08-27T22:37:44.600Z : Save file azure-devops-extension-sample-master/
2019-08-27T22:37:44.602Z : Writing buffer for azure-devops-extension-sample-master/
2019-08-27T22:37:44.602Z : Creating folder if it doesn't exist: {path}
2019-08-27T22:37:44.603Z : Save file azure-devops-extension-sample-master/.gitignore
err: Error: EISDIR: illegal operation on a directory, open '{path}/'
2019-08-27T22:37:44.604Z : Deleting contents of {path}
2019-08-27T22:37:44.604Z : Writing buffer for azure-devops-extension-sample-master/.gitignore
2019-08-27T22:37:44.604Z : Creating folder if it doesn't exist: {path}
2019-08-27T22:37:44.605Z : Error: Error unzipping {path}/azure-devops-extension-sample.zip: Error: EISDIR: illegal operation on a directory, open '{path}/'
2019-08-27T22:37:44.605Z :     at ExtensionInit.<anonymous> (/usr/local/lib/node_modules/tfx-cli/_build/exec/extension/init.js:311:31)
2019-08-27T22:37:44.605Z :     at step (/usr/local/lib/node_modules/tfx-cli/_build/exec/extension/init.js:45:23)
2019-08-27T22:37:44.605Z :     at Object.next (/usr/local/lib/node_modules/tfx-cli/_build/exec/extension/init.js:26:53)
2019-08-27T22:37:44.605Z :     at fulfilled (/usr/local/lib/node_modules/tfx-cli/_build/exec/extension/init.js:17:58)`

**Comment by raygerrard** [comment]
I am also running into this issue when trying to run the extension init command on OSX.

**Comment by StylesGumede** [comment]
So this issue has not been resolved?

**Comment by lukerider** [comment]
Any update on this? I'm getting the same error.

**Comment by nathankitchen** [comment]
Same error - can't seem to use "extension create" either.

**Comment by nbuuck** [comment]
Another contributor has opened a PR to fix this: https://github.com/microsoft/tfs-cli/pull/367
