### ISSUE TITLE
building project fails

### ISSUE THREAD

**Issue by jeffpriz** [microsoft/azure-devops-extension-sample#50]
I do a clean git clone, 

npm install
npm run compile

 npm -v 6.14.5
node -v 6.11.2

what am I missing?

ERROR in ./src/Common.scss (./node_modules/css-loader!./node_modules/azure-devops-ui/buildScripts/css-variables-loader.js!./node_modules/sass-loader/lib/loader.js!./src/Common.scss)
Module build failed (from ./node_modules/azure-devops-ui/buildScripts/css-variables-loader.js):
C:\Repos\azure-devops-extension-sample\node_modules\azure-devops-ui\buildScripts\CssVariablesLibrary.js:200
        defaults = { ...defaults, ...JSON.parse(fs.readFileSync(file, "utf8")) };
                     ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (C:\Repos\azure-devops-extension-sample\node_modules\v8-compile-cache\v8-compile-cache.js:226:18)
    at Module._compile (C:\Repos\azure-devops-extension-sample\node_modules\v8-compile-cache\v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (C:\Repos\azure-devops-extension-sample\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Repos\azure-devops-extension-sample\node_modules\azure-devops-ui\buildScripts\css-variables-loader.js:29:22)
    at Module._compile (C:\Repos\azure-devops-extension-sample\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (C:\Repos\azure-devops-extension-sample\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (C:\Repos\azure-devops-extension-sample\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Repos\azure-devops-extension-sample\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Repos\azure-devops-extension-sample\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Repos\azure-devops-extension-sample\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Repos\azure-devops-extension-sample\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Repos\azure-devops-extension-sample\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Repos\azure-devops-extension-sample\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Repos\azure-devops-extension-sample\node_modules\webpack\lib\NormalModule.js:265:3)
    at NormalModule.build (C:\Repos\azure-devops-extension-sample\node_modules\webpack\lib\NormalModule.js:412:15)
    at Compilation.buildModule (C:\Repos\azure-devops-extension-sample\node_modules\webpack\lib\Compilation.js:626:10)
    at factory.create (C:\Repos\azure-devops-extension-sample\node_modules\webpack\lib\Compilation.js:875:14)
    at factory (C:\Repos\azure-devops-extension-sample\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (C:\Repos\azure-devops-extension-sample\node_modules\webpack\lib\NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Repos\azure-devops-extension-sample\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at resolver (C:\Repos\azure-devops-extension-sample\node_modules\webpack\lib\NormalModuleFactory.js:138:29)
    at process.nextTick (C:\Repos\azure-devops-extension-sample\node_modules\webpack\lib\NormalModuleFactory.js:342:9)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./src/Common.scss 2:14-187
 @ ./src/Common.tsx
 @ ./src/Samples/Feature/Feature.tsx

**Comment by jeffpriz** [comment]
ahh.. after posting this it occurred to me that my version of Node was way old (forgot to update it back to a current version after backing up for another project)

updated node to current LTS and things are better now :)
